db:
  db_host : "107.99.46.183"
  db_port : 23307
  db_username : "app_user"
  db_password : "PqM2MNIFpvf#ugv8g"
  db_database : "mobilead"

s3:
  s3_access_key : access_key_123
  s3_secret_key : secret123
  s3_bucket : bucket123
  s3_region : region123
  presigned_url_expiry_hours : 1

email:
  smtp_server : server123
  smtp_port : 1001
  smtp_username : username1
  smtp_password : smtppass1
  sender_email : sender1@email.com
  recipient_emails :
    - email@sender.com
    - email_2@sender.com


