db:
  tvad:
    secret:
      name : "tvportal/stg/mysql"
      region : "ap-southeast-1"
  mobilead:
    secret:
      name : "mobileportal/stg/mysql"
      region : "ap-southeast-1"

s3:
  bucketName: "ssp-masssp-tvserver-report-apse1-stg"
  region: "ap-southeast-1"
  presignedUrlExpiryHours : 167

email:
  mailFrom: "akanksha.kr@stg-samsungrs.com",
  secret:
    name : "tvportal/stg/mail"
    region : "ap-southeast-1"
